-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;
-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.


CREATE TABLE pilotos (
    numero_licencia VARCHAR(20) PRIMARY KEY,
    restricciones VARCHAR(100),
    salario VARCHAR(20),
    turno VARCHAR(20)
);
CREATE TABLE hangares (
    id_hangar INT PRIMARY KEY,
    numero_hangar VARCHAR(10) NOT NULL,
    capacidad INT NOT NULL,
    localizacion VARCHAR(100) NOT NULL
);
CREATE TABLE aviones (
    id_avion INT PRIMARY KEY,
    numero_avion VARCHAR(10) NOT NULL,
    modelo VARCHAR(50) NOT NULL,
    peso VARCHAR(20) NOT NULL,
    capacidad INT NOT NULL,
    id_hangar INT,
    id_piloto VARCHAR(20),
    FOREIGN KEY (id_hangar) REFERENCES hangares(id_hangar),
    FOREIGN KEY (id_piloto) REFERENCES pilotos(numero_licencia)
);

END;